import { CardInfo } from './types';

export const deck: CardInfo[] = [
  {
    no: 'BT5-020',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT5-020.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【登場時】自分のデッキの上から3枚オープンする。その中の名称に「ガルルモン」を含むデジモンカードと名称に「オメガモン」を含むデジモンカード1枚ずつを手札に加える。残ったカードは好きな順番でデッキの下に戻す。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-020.png',
    category: 'BT05',
  },
  {
    no: 'BT5-020',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT5-020.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【登場時】自分のデッキの上から3枚オープンする。その中の名称に「ガルルモン」を含むデジモンカードと名称に「オメガモン」を含むデジモンカード1枚ずつを手札に加える。残ったカードは好きな順番でデッキの下に戻す。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-020.png',
    category: 'BT05',
  },
  {
    no: 'BT5-020',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT5-020.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【登場時】自分のデッキの上から3枚オープンする。その中の名称に「ガルルモン」を含むデジモンカードと名称に「オメガモン」を含むデジモンカード1枚ずつを手札に加える。残ったカードは好きな順番でデッキの下に戻す。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-020.png',
    category: 'BT05',
  },
  {
    no: 'BT5-020',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT5-020.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【登場時】自分のデッキの上から3枚オープンする。その中の名称に「ガルルモン」を含むデジモンカードと名称に「オメガモン」を含むデジモンカード1枚ずつを手札に加える。残ったカードは好きな順番でデッキの下に戻す。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-020.png',
    category: 'BT05',
  },
  {
    no: 'BT6-019',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT6-019.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【お互いのターン】［ターンに1回］名称に「石田ヤマト」を含む自分のテイマーが登場したとき、メモリーを+1する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］このデジモンが「ガブモン-友情の絆-」のとき、このデジモンをアクティブにできる。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-019.png',
    category: 'BT06',
  },
  {
    no: 'BT6-019',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT6-019.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【お互いのターン】［ターンに1回］名称に「石田ヤマト」を含む自分のテイマーが登場したとき、メモリーを+1する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］このデジモンが「ガブモン-友情の絆-」のとき、このデジモンをアクティブにできる。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-019.png',
    category: 'BT06',
  },
  {
    no: 'BT6-019',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT6-019.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【お互いのターン】［ターンに1回］名称に「石田ヤマト」を含む自分のテイマーが登場したとき、メモリーを+1する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］このデジモンが「ガブモン-友情の絆-」のとき、このデジモンをアクティブにできる。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-019.png',
    category: 'BT06',
  },
  {
    no: 'BT6-019',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT6-019.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect:
      '【お互いのターン】［ターンに1回］名称に「石田ヤマト」を含む自分のテイマーが登場したとき、メモリーを+1する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］このデジモンが「ガブモン-友情の絆-」のとき、このデジモンをアクティブにできる。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-019.png',
    category: 'BT06',
  },
  {
    no: 'ST2-03',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'ST2-03.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【アタック時】Lv.5以下の相手のデジモン1体の進化元を、下から1枚破棄する。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-03.png',
    category: 'ST02',
  },
  {
    no: 'ST2-03',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'ST2-03.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【アタック時】Lv.5以下の相手のデジモン1体の進化元を、下から1枚破棄する。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-03.png',
    category: 'ST02',
  },
  {
    no: 'ST2-03',
    lv: 'Lv.3',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'ST2-03.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '2000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【アタック時】Lv.5以下の相手のデジモン1体の進化元を、下から1枚破棄する。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-03.png',
    category: 'ST02',
  },
  {
    no: 'BT1-029',
    lv: 'Lv.3',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT1-029.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '1000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect: '【登場時】≪1ドロー≫（自分のデッキからカードを1枚引く）',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT01/BT1-029.png',
    category: 'BT01',
  },
  {
    no: 'BT1-029',
    lv: 'Lv.3',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'ガブモン',
    color: '2_blue',
    imgFileName: 'BT1-029.png',
    form: '成長期',
    attribute: 'データ種',
    type: '爬虫類型',
    dp: '1000',
    appearanceCost: '3',
    evolutionCost1: 'Lv.2から0',
    evolutionCost2: '-',
    effect: '【登場時】≪1ドロー≫（自分のデッキからカードを1枚引く）',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT01/BT1-029.png',
    category: 'BT01',
  },
  {
    no: 'BT5-026',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'シーラモン',
    color: '2_blue',
    imgFileName: 'BT5-026.png',
    form: '成熟期',
    attribute: 'データ種',
    type: '古代魚型',
    dp: '5000',
    appearanceCost: '6',
    evolutionCost1: 'Lv.3から1',
    evolutionCost2: '-',
    effect:
      '≪ブロッカー≫（相手のデジモンがアタックしたとき、このデジモンがアクティブ状態ならレストさせることでアタックの対象をこのデジモンにする）【アタック時】メモリーを-2する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-026.png',
    category: 'BT05',
  },
  {
    no: 'BT5-026',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'シーラモン',
    color: '2_blue',
    imgFileName: 'BT5-026.png',
    form: '成熟期',
    attribute: 'データ種',
    type: '古代魚型',
    dp: '5000',
    appearanceCost: '6',
    evolutionCost1: 'Lv.3から1',
    evolutionCost2: '-',
    effect:
      '≪ブロッカー≫（相手のデジモンがアタックしたとき、このデジモンがアクティブ状態ならレストさせることでアタックの対象をこのデジモンにする）【アタック時】メモリーを-2する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-026.png',
    category: 'BT05',
  },
  {
    no: 'BT5-026',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'シーラモン',
    color: '2_blue',
    imgFileName: 'BT5-026.png',
    form: '成熟期',
    attribute: 'データ種',
    type: '古代魚型',
    dp: '5000',
    appearanceCost: '6',
    evolutionCost1: 'Lv.3から1',
    evolutionCost2: '-',
    effect:
      '≪ブロッカー≫（相手のデジモンがアタックしたとき、このデジモンがアクティブ状態ならレストさせることでアタックの対象をこのデジモンにする）【アタック時】メモリーを-2する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-026.png',
    category: 'BT05',
  },
  {
    no: 'BT5-026',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'シーラモン',
    color: '2_blue',
    imgFileName: 'BT5-026.png',
    form: '成熟期',
    attribute: 'データ種',
    type: '古代魚型',
    dp: '5000',
    appearanceCost: '6',
    evolutionCost1: 'Lv.3から1',
    evolutionCost2: '-',
    effect:
      '≪ブロッカー≫（相手のデジモンがアタックしたとき、このデジモンがアクティブ状態ならレストさせることでアタックの対象をこのデジモンにする）【アタック時】メモリーを-2する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-026.png',
    category: 'BT05',
  },
  {
    no: 'ST2-06',
    lv: 'Lv.4',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガルルモン',
    color: '2_blue',
    imgFileName: 'ST2-06.png',
    form: '成熟期',
    attribute: 'ワクチン種',
    type: '獣型',
    dp: '4000',
    appearanceCost: '5',
    evolutionCost1: 'Lv.3から2',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【アタック時】相手のデジモン1体の進化元を、下から1枚破棄する。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-06.png',
    category: 'ST02',
  },
  {
    no: 'ST2-06',
    lv: 'Lv.4',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ガルルモン',
    color: '2_blue',
    imgFileName: 'ST2-06.png',
    form: '成熟期',
    attribute: 'ワクチン種',
    type: '獣型',
    dp: '4000',
    appearanceCost: '5',
    evolutionCost1: 'Lv.3から2',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【アタック時】相手のデジモン1体の進化元を、下から1枚破棄する。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-06.png',
    category: 'ST02',
  },
  {
    no: 'BT5-024',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'ガルルモン',
    color: '2_blue',
    imgFileName: 'BT5-024.png',
    form: '成熟期',
    attribute: 'ワクチン種',
    type: '獣型',
    dp: '5000',
    appearanceCost: '5',
    evolutionCost1: 'Lv.3から2',
    evolutionCost2: '-',
    effect:
      '【進化時】このデジモンの進化元に「ガブモン」があるとき、メモリーを+1する。',
    evolutionaryOriginEffect:
      '【お互いのターン】このデジモンが名称に「ガルルモン」か「オメガモン」を含む間、このデジモンのDPを+1000する。',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-024.png',
    category: 'BT05',
  },
  {
    no: 'BT5-024',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'ガルルモン',
    color: '2_blue',
    imgFileName: 'BT5-024.png',
    form: '成熟期',
    attribute: 'ワクチン種',
    type: '獣型',
    dp: '5000',
    appearanceCost: '5',
    evolutionCost1: 'Lv.3から2',
    evolutionCost2: '-',
    effect:
      '【進化時】このデジモンの進化元に「ガブモン」があるとき、メモリーを+1する。',
    evolutionaryOriginEffect:
      '【お互いのターン】このデジモンが名称に「ガルルモン」か「オメガモン」を含む間、このデジモンのDPを+1000する。',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-024.png',
    category: 'BT05',
  },
  {
    no: 'BT1-040',
    lv: 'Lv.5',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ワーガルルモン',
    color: '2_blue',
    imgFileName: 'BT1-040.png',
    form: '完全体',
    attribute: 'ワクチン種',
    type: '獣人型',
    dp: '7000',
    appearanceCost: '6',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】メモリーを+3する。このターン終了時、メモリーを-3する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT01/BT1-040.png',
    category: 'BT01',
  },
  {
    no: 'BT1-040',
    lv: 'Lv.5',
    rarity: 'U',
    cardtype: 'デジモン',
    name: 'ワーガルルモン',
    color: '2_blue',
    imgFileName: 'BT1-040.png',
    form: '完全体',
    attribute: 'ワクチン種',
    type: '獣人型',
    dp: '7000',
    appearanceCost: '6',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】メモリーを+3する。このターン終了時、メモリーを-3する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT01/BT1-040.png',
    category: 'BT01',
  },
  {
    no: 'ST2-08',
    lv: 'Lv.5',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'ワーガルルモン',
    color: '2_blue',
    imgFileName: 'ST2-08.png',
    form: '完全体',
    attribute: 'ワクチン種',
    type: '獣人型',
    dp: '7000',
    appearanceCost: '7',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【自分のターン】進化元を持たない相手のデジモンがいる間、このデジモンは≪セキュリティアタック+1≫（このデジモンがチェックするセキュリティの枚数+1）を得る。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-08.png',
    category: 'ST02',
  },
  {
    no: 'ST2-08',
    lv: 'Lv.5',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'ワーガルルモン',
    color: '2_blue',
    imgFileName: 'ST2-08.png',
    form: '完全体',
    attribute: 'ワクチン種',
    type: '獣人型',
    dp: '7000',
    appearanceCost: '7',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【自分のターン】進化元を持たない相手のデジモンがいる間、このデジモンは≪セキュリティアタック+1≫（このデジモンがチェックするセキュリティの枚数+1）を得る。',
    securityEffect: '-',
    imgSrc: './assets/images/ST02/ST2-08.png',
    category: 'ST02',
  },
  {
    no: 'BT6-027',
    lv: 'Lv.5',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'マジラモン',
    color: '2_blue',
    imgFileName: 'BT6-027.png',
    form: '完全体',
    attribute: 'データ種',
    type: '聖竜型/デーヴァ',
    dp: '7000',
    appearanceCost: '7',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect: '【進化時】相手のデジモン1体の進化元を、上から1枚破棄する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］進化元を持つ相手のデジモンがいないとき、このデジモンをアクティブにする。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-027.png',
    category: 'BT06',
  },
  {
    no: 'BT6-027',
    lv: 'Lv.5',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'マジラモン',
    color: '2_blue',
    imgFileName: 'BT6-027.png',
    form: '完全体',
    attribute: 'データ種',
    type: '聖竜型/デーヴァ',
    dp: '7000',
    appearanceCost: '7',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect: '【進化時】相手のデジモン1体の進化元を、上から1枚破棄する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］進化元を持つ相手のデジモンがいないとき、このデジモンをアクティブにする。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-027.png',
    category: 'BT06',
  },
  {
    no: 'BT6-027',
    lv: 'Lv.5',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'マジラモン',
    color: '2_blue',
    imgFileName: 'BT6-027.png',
    form: '完全体',
    attribute: 'データ種',
    type: '聖竜型/デーヴァ',
    dp: '7000',
    appearanceCost: '7',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect: '【進化時】相手のデジモン1体の進化元を、上から1枚破棄する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］進化元を持つ相手のデジモンがいないとき、このデジモンをアクティブにする。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-027.png',
    category: 'BT06',
  },
  {
    no: 'BT6-027',
    lv: 'Lv.5',
    rarity: 'R',
    cardtype: 'デジモン',
    name: 'マジラモン',
    color: '2_blue',
    imgFileName: 'BT6-027.png',
    form: '完全体',
    attribute: 'データ種',
    type: '聖竜型/デーヴァ',
    dp: '7000',
    appearanceCost: '7',
    evolutionCost1: 'Lv.4から3',
    evolutionCost2: '-',
    effect: '【進化時】相手のデジモン1体の進化元を、上から1枚破棄する。',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］進化元を持つ相手のデジモンがいないとき、このデジモンをアクティブにする。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-027.png',
    category: 'BT06',
  },
  {
    no: 'BT5-032',
    lv: 'Lv.6',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ヘクセブラウモン',
    color: '2_blue',
    imgFileName: 'BT5-032.png',
    form: '究極体',
    attribute: 'データ種',
    type: '魔法騎士型',
    dp: '11000',
    appearanceCost: '12',
    evolutionCost1: 'Lv.5から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】相手のデジモン1体の進化元を、下から2枚まで破棄する。その後、進化元を持たない相手のデジモンがいるとき、このターンの間、このデジモンは≪ジャミング≫（このデジモンはセキュリティデジモンとのバトルでは消滅しない）を得る。【お互いのターン】進化元を持たない相手のデジモン全てはアタックとブロックができない。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-032.png',
    category: 'BT05',
  },
  {
    no: 'BT5-032',
    lv: 'Lv.6',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ヘクセブラウモン',
    color: '2_blue',
    imgFileName: 'BT5-032.png',
    form: '究極体',
    attribute: 'データ種',
    type: '魔法騎士型',
    dp: '11000',
    appearanceCost: '12',
    evolutionCost1: 'Lv.5から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】相手のデジモン1体の進化元を、下から2枚まで破棄する。その後、進化元を持たない相手のデジモンがいるとき、このターンの間、このデジモンは≪ジャミング≫（このデジモンはセキュリティデジモンとのバトルでは消滅しない）を得る。【お互いのターン】進化元を持たない相手のデジモン全てはアタックとブロックができない。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-032.png',
    category: 'BT05',
  },
  {
    no: 'BT5-032',
    lv: 'Lv.6',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ヘクセブラウモン',
    color: '2_blue',
    imgFileName: 'BT5-032.png',
    form: '究極体',
    attribute: 'データ種',
    type: '魔法騎士型',
    dp: '11000',
    appearanceCost: '12',
    evolutionCost1: 'Lv.5から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】相手のデジモン1体の進化元を、下から2枚まで破棄する。その後、進化元を持たない相手のデジモンがいるとき、このターンの間、このデジモンは≪ジャミング≫（このデジモンはセキュリティデジモンとのバトルでは消滅しない）を得る。【お互いのターン】進化元を持たない相手のデジモン全てはアタックとブロックができない。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-032.png',
    category: 'BT05',
  },
  {
    no: 'BT5-032',
    lv: 'Lv.6',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ヘクセブラウモン',
    color: '2_blue',
    imgFileName: 'BT5-032.png',
    form: '究極体',
    attribute: 'データ種',
    type: '魔法騎士型',
    dp: '11000',
    appearanceCost: '12',
    evolutionCost1: 'Lv.5から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】相手のデジモン1体の進化元を、下から2枚まで破棄する。その後、進化元を持たない相手のデジモンがいるとき、このターンの間、このデジモンは≪ジャミング≫（このデジモンはセキュリティデジモンとのバトルでは消滅しない）を得る。【お互いのターン】進化元を持たない相手のデジモン全てはアタックとブロックができない。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-032.png',
    category: 'BT05',
  },
  {
    no: 'BT5-025',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'ペイルドラモン',
    color: '2_blue',
    imgFileName: 'BT5-025.png',
    form: '成熟期',
    attribute: 'データ種',
    type: '竜型',
    dp: '4000',
    appearanceCost: '5',
    evolutionCost1: 'Lv.3から2',
    evolutionCost2: '-',
    effect: '【進化時】相手のデジモン1体の進化元を、下から2枚まで破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-025.png',
    category: 'BT05',
  },
  {
    no: 'BT5-025',
    lv: 'Lv.4',
    rarity: 'C',
    cardtype: 'デジモン',
    name: 'ペイルドラモン',
    color: '2_blue',
    imgFileName: 'BT5-025.png',
    form: '成熟期',
    attribute: 'データ種',
    type: '竜型',
    dp: '4000',
    appearanceCost: '5',
    evolutionCost1: 'Lv.3から2',
    evolutionCost2: '-',
    effect: '【進化時】相手のデジモン1体の進化元を、下から2枚まで破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT05/BT5-025.png',
    category: 'BT05',
  },
  {
    no: 'BT6-030',
    lv: 'Lv.7',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ガブモン-友情の絆-',
    color: '2_blue',
    imgFileName: 'BT6-030.png',
    form: '究極体',
    attribute: '不明',
    type: '不明',
    dp: '14000',
    appearanceCost: '14',
    evolutionCost1: 'Lv.6から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】［ターンに1回］自分のテイマーがいるとき、このデジモンをアクティブにできる。【アタック時】Lv.5以下の相手のデジモン1体をデッキの下に戻す。そのデジモンの持つ進化元は破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-030.png',
    category: 'BT06',
  },
  {
    no: 'BT6-030',
    lv: 'Lv.7',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ガブモン-友情の絆-',
    color: '2_blue',
    imgFileName: 'BT6-030.png',
    form: '究極体',
    attribute: '不明',
    type: '不明',
    dp: '14000',
    appearanceCost: '14',
    evolutionCost1: 'Lv.6から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】［ターンに1回］自分のテイマーがいるとき、このデジモンをアクティブにできる。【アタック時】Lv.5以下の相手のデジモン1体をデッキの下に戻す。そのデジモンの持つ進化元は破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-030.png',
    category: 'BT06',
  },
  {
    no: 'BT6-030',
    lv: 'Lv.7',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ガブモン-友情の絆-',
    color: '2_blue',
    imgFileName: 'BT6-030.png',
    form: '究極体',
    attribute: '不明',
    type: '不明',
    dp: '14000',
    appearanceCost: '14',
    evolutionCost1: 'Lv.6から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】［ターンに1回］自分のテイマーがいるとき、このデジモンをアクティブにできる。【アタック時】Lv.5以下の相手のデジモン1体をデッキの下に戻す。そのデジモンの持つ進化元は破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-030.png',
    category: 'BT06',
  },
  {
    no: 'BT6-030',
    lv: 'Lv.7',
    rarity: 'SR',
    cardtype: 'デジモン',
    name: 'ガブモン-友情の絆-',
    color: '2_blue',
    imgFileName: 'BT6-030.png',
    form: '究極体',
    attribute: '不明',
    type: '不明',
    dp: '14000',
    appearanceCost: '14',
    evolutionCost1: 'Lv.6から3',
    evolutionCost2: '-',
    effect:
      '【アタック時】［ターンに1回］自分のテイマーがいるとき、このデジモンをアクティブにできる。【アタック時】Lv.5以下の相手のデジモン1体をデッキの下に戻す。そのデジモンの持つ進化元は破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-030.png',
    category: 'BT06',
  },
  {
    no: 'BT6-002',
    lv: 'Lv.2',
    rarity: 'U',
    cardtype: 'デジタマ',
    name: 'キャロモン',
    color: '2_blue',
    imgFileName: 'BT6-002.png',
    form: '幼年期',
    attribute: '-',
    type: 'レッサー型',
    dp: '-',
    appearanceCost: '-',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【自分のターン】［ターンに1回］相手のデジモンの進化元を破棄したとき、≪1ドロー≫（自分のデッキからカードを1枚引く）。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-002.png',
    category: 'BT06',
  },
  {
    no: 'BT6-002',
    lv: 'Lv.2',
    rarity: 'U',
    cardtype: 'デジタマ',
    name: 'キャロモン',
    color: '2_blue',
    imgFileName: 'BT6-002.png',
    form: '幼年期',
    attribute: '-',
    type: 'レッサー型',
    dp: '-',
    appearanceCost: '-',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【自分のターン】［ターンに1回］相手のデジモンの進化元を破棄したとき、≪1ドロー≫（自分のデッキからカードを1枚引く）。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-002.png',
    category: 'BT06',
  },
  {
    no: 'BT6-002',
    lv: 'Lv.2',
    rarity: 'U',
    cardtype: 'デジタマ',
    name: 'キャロモン',
    color: '2_blue',
    imgFileName: 'BT6-002.png',
    form: '幼年期',
    attribute: '-',
    type: 'レッサー型',
    dp: '-',
    appearanceCost: '-',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【自分のターン】［ターンに1回］相手のデジモンの進化元を破棄したとき、≪1ドロー≫（自分のデッキからカードを1枚引く）。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-002.png',
    category: 'BT06',
  },
  {
    no: 'BT6-002',
    lv: 'Lv.2',
    rarity: 'U',
    cardtype: 'デジタマ',
    name: 'キャロモン',
    color: '2_blue',
    imgFileName: 'BT6-002.png',
    form: '幼年期',
    attribute: '-',
    type: 'レッサー型',
    dp: '-',
    appearanceCost: '-',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【自分のターン】［ターンに1回］相手のデジモンの進化元を破棄したとき、≪1ドロー≫（自分のデッキからカードを1枚引く）。',
    securityEffect: '-',
    imgSrc: './assets/images/BT06/BT6-002.png',
    category: 'BT06',
  },
  {
    no: 'BT1-003',
    lv: 'Lv.2',
    rarity: 'R',
    cardtype: 'デジタマ',
    name: 'ウパモン',
    color: '2_blue',
    imgFileName: 'BT1-003.png',
    form: '幼年期',
    attribute: '-',
    type: '両生類型',
    dp: '-',
    appearanceCost: '-',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '-',
    evolutionaryOriginEffect:
      '【アタック時】［ターンに1回］進化元を持たない相手のデジモンがいるとき、≪1ドロー≫（自分のデッキからカードを1枚引く）。',
    securityEffect: '-',
    imgSrc: './assets/images/BT01/BT1-003.png',
    category: 'BT01',
  },
  {
    no: 'BT6-088',
    rarity: 'R',
    cardtype: 'テイマー',
    name: '石田ヤマト',
    color: '2_blue',
    imgFileName: 'BT6-088.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '3',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【自分のターン】名称に「ガブモン」か「ガルルモン」を含む自分のデジモンが育成エリアからバトルエリアに移動したとき、メモリーを+1して、≪1ドロー≫（自分のデッキからカードを1枚引く）。【メイン】［ターンに1回］自分の「ガブモン」1体を、手札の「ガブモン-友情の絆-」に、Lv.を無視して進化コストを支払って進化させる。そうしたとき、自分のセキュリティを上から2枚破棄する。その後、自分のセキュリティが1枚以上なら、このターン終了時、そのデジモンを消滅させる。',
    evolutionaryOriginEffect: '-',
    securityEffect:
      '【セキュリティ】このカードをコストを支払わずに登場させる。',
    imgSrc: './assets/images/BT06/BT6-088.png',
    category: 'BT06',
  },
  {
    no: 'BT6-088',
    rarity: 'R',
    cardtype: 'テイマー',
    name: '石田ヤマト',
    color: '2_blue',
    imgFileName: 'BT6-088.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '3',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【自分のターン】名称に「ガブモン」か「ガルルモン」を含む自分のデジモンが育成エリアからバトルエリアに移動したとき、メモリーを+1して、≪1ドロー≫（自分のデッキからカードを1枚引く）。【メイン】［ターンに1回］自分の「ガブモン」1体を、手札の「ガブモン-友情の絆-」に、Lv.を無視して進化コストを支払って進化させる。そうしたとき、自分のセキュリティを上から2枚破棄する。その後、自分のセキュリティが1枚以上なら、このターン終了時、そのデジモンを消滅させる。',
    evolutionaryOriginEffect: '-',
    securityEffect:
      '【セキュリティ】このカードをコストを支払わずに登場させる。',
    imgSrc: './assets/images/BT06/BT6-088.png',
    category: 'BT06',
  },
  {
    no: 'BT6-088',
    rarity: 'R',
    cardtype: 'テイマー',
    name: '石田ヤマト',
    color: '2_blue',
    imgFileName: 'BT6-088.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '3',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【自分のターン】名称に「ガブモン」か「ガルルモン」を含む自分のデジモンが育成エリアからバトルエリアに移動したとき、メモリーを+1して、≪1ドロー≫（自分のデッキからカードを1枚引く）。【メイン】［ターンに1回］自分の「ガブモン」1体を、手札の「ガブモン-友情の絆-」に、Lv.を無視して進化コストを支払って進化させる。そうしたとき、自分のセキュリティを上から2枚破棄する。その後、自分のセキュリティが1枚以上なら、このターン終了時、そのデジモンを消滅させる。',
    evolutionaryOriginEffect: '-',
    securityEffect:
      '【セキュリティ】このカードをコストを支払わずに登場させる。',
    imgSrc: './assets/images/BT06/BT6-088.png',
    category: 'BT06',
  },
  {
    no: 'BT6-097',
    rarity: 'U',
    cardtype: 'オプション',
    name: 'ハウリング・メモリーブースト！！',
    color: '2_blue',
    imgFileName: 'BT6-097.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '3',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【メイン】相手のデジモン1体の進化元を、下から2枚破棄する。その後、次の相手のターン終了時まで、進化元を持たない相手のデジモン1体はアタックとブロックができない。その後、このカードをバトルエリアに置く。【メイン】≪ディレイ≫（バトルエリアのこのカードを破棄することで、以下の効果を発揮する。この効果はこのカードを置いたターンには発揮できない）・メモリーを+2する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '【セキュリティ】このカードをバトルエリアに置く。',
    imgSrc: './assets/images/BT06/BT6-097.png',
    category: 'BT06',
  },
  {
    no: 'BT6-097',
    rarity: 'U',
    cardtype: 'オプション',
    name: 'ハウリング・メモリーブースト！！',
    color: '2_blue',
    imgFileName: 'BT6-097.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '3',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【メイン】相手のデジモン1体の進化元を、下から2枚破棄する。その後、次の相手のターン終了時まで、進化元を持たない相手のデジモン1体はアタックとブロックができない。その後、このカードをバトルエリアに置く。【メイン】≪ディレイ≫（バトルエリアのこのカードを破棄することで、以下の効果を発揮する。この効果はこのカードを置いたターンには発揮できない）・メモリーを+2する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '【セキュリティ】このカードをバトルエリアに置く。',
    imgSrc: './assets/images/BT06/BT6-097.png',
    category: 'BT06',
  },
  {
    no: 'BT6-098',
    rarity: 'R',
    cardtype: 'オプション',
    name: 'レドルスター',
    color: '2_blue',
    imgFileName: 'BT6-098.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '5',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【メイン】Lv.5以下の相手のデジモン1体を手札に戻す。相手のデジモンが3体以上いるとき、代わりに相手のデジモン1体をデッキの下に戻す。そのデジモンの持つ進化元は破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '【セキュリティ】このカードの【メイン】効果を発揮する。',
    imgSrc: './assets/images/BT06/BT6-098.png',
    category: 'BT06',
  },
  {
    no: 'BT6-098',
    rarity: 'R',
    cardtype: 'オプション',
    name: 'レドルスター',
    color: '2_blue',
    imgFileName: 'BT6-098.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '5',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【メイン】Lv.5以下の相手のデジモン1体を手札に戻す。相手のデジモンが3体以上いるとき、代わりに相手のデジモン1体をデッキの下に戻す。そのデジモンの持つ進化元は破棄する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '【セキュリティ】このカードの【メイン】効果を発揮する。',
    imgSrc: './assets/images/BT06/BT6-098.png',
    category: 'BT06',
  },
  {
    no: 'BT3-093',
    rarity: 'R',
    cardtype: 'テイマー',
    name: '本宮大輔',
    color: '2_blue',
    imgFileName: 'BT3-093.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '4',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【自分のターン開始時】自分のメモリーが2以下のとき、3にする。【登場時】自分のデッキの上から3枚オープンする。その中の青と緑のデジモンカード1枚ずつを手札に加える。残ったカードは好きな順番でデッキの下に戻す。',
    evolutionaryOriginEffect: '-',
    securityEffect:
      '【セキュリティ】このカードをコストを支払わずに登場させる。',
    imgSrc: './assets/images/BT03/BT3-093.png',
    category: 'BT03',
  },
  {
    no: 'BT3-093',
    rarity: 'R',
    cardtype: 'テイマー',
    name: '本宮大輔',
    color: '2_blue',
    imgFileName: 'BT3-093.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '4',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect:
      '【自分のターン開始時】自分のメモリーが2以下のとき、3にする。【登場時】自分のデッキの上から3枚オープンする。その中の青と緑のデジモンカード1枚ずつを手札に加える。残ったカードは好きな順番でデッキの下に戻す。',
    evolutionaryOriginEffect: '-',
    securityEffect:
      '【セキュリティ】このカードをコストを支払わずに登場させる。',
    imgSrc: './assets/images/BT03/BT3-093.png',
    category: 'BT03',
  },
  {
    no: 'ST2-13',
    rarity: 'C',
    cardtype: 'オプション',
    name: 'ハンマースパーク',
    color: '2_blue',
    imgFileName: 'ST2-13.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '0',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '【メイン】メモリーを+1する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '【セキュリティ】メモリーを+2する。',
    imgSrc: './assets/images/ST02/ST2-13.png',
    category: 'ST02',
  },
  {
    no: 'ST2-13',
    rarity: 'C',
    cardtype: 'オプション',
    name: 'ハンマースパーク',
    color: '2_blue',
    imgFileName: 'ST2-13.png',
    form: '-',
    attribute: '-',
    type: '-',
    dp: '-',
    appearanceCost: '0',
    evolutionCost1: '-',
    evolutionCost2: '-',
    effect: '【メイン】メモリーを+1する。',
    evolutionaryOriginEffect: '-',
    securityEffect: '【セキュリティ】メモリーを+2する。',
    imgSrc: './assets/images/ST02/ST2-13.png',
    category: 'ST02',
  },
];
